### ISSUE TITLE
Setup issue, not adding classes.

### ISSUE THREAD

**Issue by sephorra** [nilsenpaul/redactoraddattributes#2]
Does this plugin work with version  2.3.2624 of Craft? I installed and set up json with your example and updated the redactor json file and it doesn't seem to be adding the classes. I don't have any php errors in the log so I'm not sure where i'm going wrong. Any advice you can give would be great!

Thanks

**Comment by julzmon** [comment]
It stopped working for me also.

**Comment by nilsenpaul** [comment]
Sorry for that. I don't have time to fix this now, but if you could pinpoint the problem, I would be more than happy to alter the files.

**Comment by nilsenpaul** [comment]
Added this solution, not tested (yet).
